name: Build and deploy Node.js app to Azure Web App - e-voting123

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Install and build frontend
      - name: Install frontend dependencies
        working-directory: ./backend/frontend
        run: npm install

      - name: Build frontend
        working-directory: ./backend/frontend
        run: npm run build

      # Upload only the backend (with built frontend) for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v1.4.6 # Revert to a stable version of the action
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_89249204187B4C9996E280FC501ED369 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE51181A966640D6A7F57951597C203F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93C577B3791C461EB23E971B9BD826EA }}
          # enable-oidc is not an input for v1.x and was invalid for v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'e-voting123'
          slot-name: 'Production'
          package: .
